name: Metrics
on:
  # Allow manual trigger
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 3D Isometric Calendar & Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          
          # Options for the 3D graph
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Commit the result back to your repo
          config_timezone: Asia/Kolkata
